name: base_starter
description: >
  Highly scalable Flutter starter kit, designed with an optimal predefined structure 
  and inclusive of libraries that are widely applicable in numerous use cases.
publish_to: "none"
version: 0.0.1+1

environment:
  sdk: ">=3.4.1 <4.0.0"

dependencies:
  # Flutter SDK
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Core
  firebase_core: ^3.10.0
  firebase_analytics: ^11.4.0
  firebase_crashlytics: ^4.3.0

  # Stream
  stream_transform: ^2.1.0
  rxdart: ^0.27.7
  meta: any
  analyzer: any

  # BLoC
  flutter_bloc: ^9.0.0
  bloc: ^9.0.0
  bloc_concurrency: ^0.3.0

  # Networking
  dio: ^5.6.0

  # Persisting
  shared_preferences: ^2.3.2
  firebase_storage: ^12.4.0
  flutter_cache_manager: ^3.4.1

  # Logging
  ispect: ^3.0.0-dev.3
  ispectify_dio: 0.0.1-dev.2
  ispectify_bloc: 0.0.1-dev.4

  # Utils
  url_launcher: ^6.3.1
  mime: ^2.0.0
  pure: ^0.3.0
  platform_info: ^4.0.2
  path: ^1.9.0
  path_provider: ^2.1.5
  mocktail: ^1.0.4
  equatable: ^2.0.5
  share_plus: ^10.1.2
  package_info_plus: ^8.0.2
  device_info_plus: ^10.1.2

  # UI
  ui:
    path: packages/ui
  gap: ^3.0.1
  group_button: ^5.3.4
  flutter_easyloading: ^3.0.5
  auto_size_text: ^3.0.0
  iconsax_plus: ^1.0.0

  # Routing
  octopus: ^0.0.9

  # Others
  provider: ^6.1.2
  flutter_secure_storage: ^9.2.2
  envied: ^0.5.4
  dev: ^1.0.0

  custom_lint: ^0.6.4

dev_dependencies:
  # Testing
  flutter_test:
    sdk: flutter

  # Lints
  pyramid_lint: ^2.0.0

  # Utils
  flutter_gen_runner: ^5.6.0
  flutter_native_splash: ^2.4.1
  flutter_launcher_icons: ^0.13.1

  # Flavors
  flutter_flavorizr: ^2.2.3

  # Codegen
  drift_dev: ^2.18.0
  build_runner: ^2.4.11
  envied_generator: ^0.5.4

dart_obfuscation: true
flutter:
  uses-material-design: true

  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - assets/fonts/
    - .env

  fonts:
    - family: Gilroy
      fonts:
        - asset: assets/fonts/Gilroy-Black.ttf
        - asset: assets/fonts/Gilroy-Bold.ttf
        - asset: assets/fonts/Gilroy-Extrabold.ttf
        - asset: assets/fonts/Gilroy-Heavy.ttf
        - asset: assets/fonts/Gilroy-Regular.ttf
        - asset: assets/fonts/Gilroy-Semibold.ttf
        - asset: assets/fonts/Gilroy-Thin.ttf
        - asset: assets/fonts/Gilroy-UltraLight.ttf
        - asset: assets/fonts/Gilroy-Medium.ttf
        - asset: assets/fonts/Gilroy-Light.ttf

flutter_gen:
  output: lib/src/core/assets/generated
  line_length: 80

flutter_launcher_icons: # dart run flutter_launcher_icons
  #  image_path: "assets/images/icon-128x128.png"
  image_path_android: "assets/images/launcher.png"
  image_path_ios: "assets/images/launcher.png"
  android: true # can specify file name here e.g. "ic_launcher"
  ios: true # can specify file name here e.g. "My-Launcher-Icon"
  # adaptive_icon_background: "assets/images/christmas-background.png" # only available for Android 8.0 devices and above
  # adaptive_icon_foreground: "assets/images/icon-foreground-432x432.png" # only available for Android 8.0 devices and above
  min_sdk_android: 21 # android min sdk min:16, default 21
  remove_alpha_ios: true

  # web:
  #   generate: true
  #   image_path: "assets/images/launcher.png"
  #   # background_color: "#hexcode"
  #   # theme_color: "#hexcode"

  # windows:
  #   generate: true
  #   image_path: "assets/images/launcher.png"
  #   icon_size: 48 # min:48, max:256, default: 48

  # macos:
  #   generate: true
  #   image_path: "assets/images/launcher.png"
